### ISSUE TITLE
No JAR file in our CLI for Node.js

### ISSUE THREAD

**Issue by Rvice** [oracle/netsuite-suitecloud-sdk#580]
### Your environment
**OS** : Ubuntu 20.04.2 LTS
**Node.js version** : 14.17.4
**suitecloud-cli version** : 1.5.0
**Terminal/CMD tool** : Bash

### Describe the bug
With previous versions our CI TeamCity would perform account setup without issues. Now, the following error is received:
There is no JAR file in your CLI for Node.js. Run "npm install" from "/home/me/.nvm/versions/node/v14.17.4/lib/node_modules/@oracle/suitecloud-cli" to install the JAR file.](https://github.com/oracle/netsuite-suitecloud-sdk/issues/420)

### To Reproduce
1. suitecloud account:setup -i
2. Observe error

### Actual Behavior
There is no JAR file in your CLI for Node.js. Run "npm install" from "/home/me/.nvm/versions/node/v14.17.4/lib/node_modules/@oracle/suitecloud-cli" to install the JAR file.](https://github.com/oracle/netsuite-suitecloud-sdk/issues/420)

### Expected Behavior
Expect it to make the prompt for Browser or Token auth

### Additional context
This does work in Windows environments

**Comment by eklonsousa** [comment]
Same behavior here without  ` sudo` command before `suitecloud`...

**Comment by alii-gator** [comment]
@eklonsousa Are you still getting this issue?

**Comment by shannonmccleary-ihm** [comment]
We are getting this with the latest CLI version `1.6.0` on Windows. I have 4 new devs at a standstill while the devs coding in repos that use `1.0.4` are not impacted. Bout to open a ticket with NS. 

We have gone thru disabling proxies, checking certs and CAs, admin vs non-admin, new machine w/ fresh node.js vs old machine w/ node.js, re-installing node and cant get past this missing JAR error and the `unable to get local issuer certificate` error

**Comment by alii-gator** [comment]
@shannonmccleary-ihm What error are you getting?
Not that `1.6.0` requires java 17?
Can you confirm that Devs having issue have java 17 installed?
If not, please install 17 and then try installing `npm i @oracle/suitecloud-cli`

**Comment by shannonmccleary-ihm** [comment]
@alii-gator we started from scratch on the new machines and also performed the tasks below but still getting the same errors. Any tips would be greatly appreciated
- removed all node_modules in Roaming and in the local sourcecode folder
- installed JDK 17
- installed using `npm i @oracle/suitecloud-cli` instead of `npm i @oracle/suitecloud-cli@1.0.4`

**Java Version**
```
$ java -version
java version "17.0.4.1" 2022-08-18 LTS
Java(TM) SE Runtime Environment (build 17.0.4.1+1-LTS-2)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4.1+1-LTS-2, mixed mode, sharing)
```

**Tail of Node Error Log**
```
...
354 timing reify:unpack Completed in 2738ms
355 timing reify:unretire Completed in 0ms
356 timing build:queue Completed in 2ms
357 timing build:link:node_modules/@oracle/suitecloud-cli Completed in 6ms
358 timing build:link:node_modules/@oracle/suitecloud-cli/node_modules/vm2 Completed in 5ms
359 timing build:link:node_modules/@oracle/suitecloud-cli/node_modules/acorn Completed in 6ms
360 timing build:link Completed in 6ms
361 info run @oracle/suitecloud-cli@1.6.0 postinstall node_modules/@oracle/suitecloud-cli node postinstall.js
362 info run @oracle/suitecloud-cli@1.6.0 postinstall { code: 4294967295, signal: null }
363 timing reify:rollback:createSparse Completed in 1414ms
364 timing reify:rollback:retireShallow Completed in 0ms
365 timing command:install Completed in 6994ms
366 verbose stack Error: command failed
366 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:63:27)
366 verbose stack     at ChildProcess.emit (node:events:513:28)
366 verbose stack     at maybeClose (node:internal/child_process:1093:16)
366 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
367 verbose pkgid @oracle/suitecloud-cli@1.6.0
368 verbose cwd C:\Users\1133263\WebstormProjects\NetSuite
369 verbose Windows_NT 10.0.19044
370 verbose node v16.17.0
371 verbose npm  v8.15.0
372 error code 4294967295
373 error path C:\Users\1133263\AppData\Roaming\npm\node_modules\@oracle\suitecloud-cli
374 error command failed
375 error command C:\Windows\system32\cmd.exe /d /s /c C:\Users\1133263\AppData\Local\Temp\postinstall-20f08e54.cmd
376 error There was an error when downloading SuiteCloud SDK dependency from https://system.netsuite.com/download/suitecloud-sdk/22.2/cli-2022.2.0.jar
376 error Error: unable to get local issuer certificate
377 verbose exit 4294967295
378 timing npm Completed in 7084ms
379 verbose unfinished npm timer reify 1663255247171
380 verbose unfinished npm timer reify:build 1663255252116
381 verbose unfinished npm timer build 1663255252116
382 verbose unfinished npm timer build:deps 1663255252117
383 verbose unfinished npm timer build:run:postinstall 1663255252125
384 verbose unfinished npm timer build:run:postinstall:node_modules/@oracle/suitecloud-cli 1663255252125
385 verbose code 4294967295
386 error A complete log of this run can be found in:
386 error     C:\Users\1133263\AppData\Local\npm-cache\_logs\2022-09-15T15_20_47_083Z-debug-0.log
```

**Comment by shannonmccleary-ihm** [comment]
@Rvice Yes we tried that as well. This is for a manual install on a new windows laptop

**Comment by alii-gator** [comment]
@shannonmccleary-ihm 
Ok lets check few more things.
Can you please check that node 16 LTS is installed. 
Can you try installation with global flag? 
npm install -g @oracle/suitecloud-cli

**Comment by shannonmccleary-ihm** [comment]
@alii-gator Indeed, we have tried global and non-global variations of the install command. We have also tried installing it locally in the project by adding it to `package.json` and running `npm install`. Node is v16 LTS and JDK is v17
```
verbose Windows_NT 10.0.19044
verbose node v16.17.0
verbose npm  v8.15.0
java version "17.0.4.1" 2022-08-18 LTS
Java(TM) SE Runtime Environment (build 17.0.4.1+1-LTS-2)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4.1+1-LTS-2, mixed mode, sharing)
```
We have our support team checking if the `unable to get local issuer certificate` may be due to a proxy/firewall caused by corp firewall software on these new machines. Thank you again for your help!

**Comment by shannonmccleary-ihm** [comment]
@alii-gator yes we can install other modules without any issues

**Comment by alii-gator** [comment]
@shannonmccleary-ihm Ok, I think its an issue on your machine. Hopefully you can fix this.
just an FYI: 
https://stackoverflow.com/questions/36494336/npm-install-error-unable-to-get-local-issuer-certificate

**Comment by shannonmccleary-ihm** [comment]
@alii-gator  @Rvice Great news! There were indeed some proxy issues with ZScaler, installed in all new machines. We got it resolved with our support and was able to install the module with no errors after they added some rules and "magic". Thank you again for tips! You guys rock

**Comment by Rvice** [comment]
FYI, still having the issue with Java 17, but still not on node 16. Node 14. When I can get a chance to update our CI/CD to 16 I'll test again.

Just tried 1.6.1 on Linux. Note, Windows works fine.

**Comment by eklonsousa** [comment]
> @eklonsousa Are you still getting this issue?

Yes! I'm still facing the issue with a new machine and another OS (OSx). 

`src % suitecloud project:validate `
Unexpected error encountered.

**Comment by vic-nik** [comment]
@eklonsousa Hi, the original error reported for this issue was different from "Unexpected error encountered". Are you sure the current error is related to downloading JAR dependency?
As for the JAR dependency there is no issue with JAR availability, if you have the problem downloading it it is most likely related to your environment setup (proxy, vpn, file system permissions). You may want to re-install the CLI on public network (with proxy or VPN disabled), please also make sure you use the documented JDK and Node.js versions.
